### ISSUE TITLE
Магические числа в workshop2

### ISSUE THREAD

**Issue by sergey-shambir** [MapmakerLich/Labs#6]
В коде есть магические числа 40, 600, 800, они повторяются несколько раз. Непонятно, как они связаны, в каком диапазоне их можно менять, какое у них назначение. Предлагаю магические числа заменить на глобальные константы.

**Comment by sergey-shambir** [comment]
Название функции random_float не соответствует стилю кодирования. Это по большому счёту моя ошибка, в статье [cxx_random](https://ps-group.github.io/cxx/cxx_random) я её поправил, и здесь тоже следует поменять название, например, на getRandomFloat

**Comment by MapmakerLich** [comment]
fixed
